SELECT *
FROM SVC_DA_REP.AGG_DDU_DAILY_DATA_USAGE
WHERE TRUNC(DDU_EVENT_TIME) = TRUNC(SYSDATE - 1)
FETCH FIRST 20 ROWS ONLY

-- 

SELECT *
FROM SVC_DA_REP.AGG_DSU_DAILY_SMS_USAGE
FETCH FIRST 20 ROWS ONLY

-- 

SELECT *
FROM BO.VW_DDR_DRLL_DOWN_RECHARGE 
FETCH FIRST 20 ROWS ONLY

-- 

SELECT 
/*+PARALLEL(15)*/
*
FROM BO.VW_MPESA_VIEW M
 WHERE M.EVENT_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
   AND M.EVENT_DATE < TRUNC(SYSDATE);