--- Customer e Traffic
  SELECT /*+PARALLEL(15)*/
 TRUNC(DC_DATE, 'MM') PP_MONTH,
 BO.GET_WEEK_NUM(DC_DATE) WEEK_NUM,
 BO.GET_SAME_DAY(DC_DATE) SAME_DAY,
 TO_CHAR(DC_DATE, 'DY') WEEK_DAY,
 BO.GET_DATE_MTD(DC_DATE) DATE_MTD,
 D.DC_DATE,
 D.EVENT_DESCRIPTION,
 SUM(D.DC_PREPAD) DC_PREPAD,
 SUM(D.DC_HYBRID) DC_HYBRID,
 SUM(D.DC_TOTAL) DC_TOTAL,
 D.DC_PROVINCE,
 D.DC_SEGMENT,
 NULL,
 TO_CHAR(TRUNC(DC_DATE, 'mm'), 'MM') MMONTH,
 TO_CHAR(TRUNC(DC_DATE, 'dd'), 'DD') DDATE,
 TO_CHAR(TRUNC(DC_DATE, 'yyyy'), 'YYYY') YYEAR
  FROM BO.V_DRA_DAILY_CUSTOMERS_SELECT D
 WHERE DC_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
   AND DC_DATE < TRUNC(SYSDATE)
 GROUP BY TRUNC(DC_DATE, 'MM'),
          BO.GET_WEEK_NUM(DC_DATE),
          BO.GET_SAME_DAY(DC_DATE),
          TO_CHAR(DC_DATE, 'DY'),
          BO.GET_DATE_MTD(DC_DATE),
          D.DC_DATE,
          D.EVENT_DESCRIPTION,
          D.DC_PROVINCE,
          D.DC_SEGMENT;
          
-- Revenue
SELECT
  /*+PARALLEL(15)*/
  TRUNC(OC_DATE, 'MM') PP_MONTH,  
  BO.GET_WEEK_NUM(OC_DATE) WEEK_NUM,
  BO.GET_SAME_DAY(OC_DATE) SAME_DAY,
  TO_CHAR(OC_DATE, 'DY') WEEK_DAY,
  BO.GET_DATE_MTD(OC_DATE) DATE_MTD,
  OC_DATE,
  SERVICE_NAME,
  DR_PREPAID,
  DR_HYBRID,
  DR_TOTAL,
  NVL(PROVINCE, 'UNKNOWN') PROVINCE,
  BUSINESS_SEGMENT,
  NULL,
  TO_CHAR(TRUNC(OC_DATE, 'mm'), 'MM') MMONTH,
  TO_CHAR(TRUNC(OC_DATE, 'dd'), 'DD') DDATE,
  TO_CHAR(TRUNC(OC_DATE, 'yyyy'), 'YYYY') YYEAR
   FROM BO.V_DRA_DAILY_REVENUE_SELECT_VW D
  WHERE OC_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
    AND OC_DATE < TRUNC(SYSDATE)

----- Recharge ------
SELECT
 /*+PARALLEL(10)*/
 TRUNC(BPM_START_DATE, 'MM') PP_MONTH,
 BO.GET_WEEK_NUM(BPM_START_DATE) WEEK_NUM,
 BO.GET_SAME_DAY(BPM_START_DATE) SAME_DAY,
 TO_CHAR(BPM_START_DATE, 'DY') WEEK_DAY,
 BO.GET_DATE_MTD(BPM_START_DATE) DATE_MTD,
 R.BPM_START_DATE,
 R.CHANNEL,
 R.REV_PREPAID,
 R.REV_HYBRID,
 R.BPM_REVENUE,
 NULL,
 NULL,
 NULL,
 TO_CHAR(TRUNC(BPM_START_DATE, 'mm'), 'MM') MMONTH,
 TO_CHAR(TRUNC(BPM_START_DATE, 'dd'), 'DD') DDATE,
 TO_CHAR(TRUNC(BPM_START_DATE, 'yyyy'), 'YYYY') YYEAR
  FROM BO.VW_DDR_DRLL_DOWN_RECHARGE R
 WHERE BPM_START_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5) 
 AND R.BPM_START_DATE < TRUNC(SYSDATE);
   
    
---- Mpesa
SELECT
/*+PARALLEL(10)*/
 TRUNC(EVENT_DATE, 'MM') PP_MONTH,
 BO.GET_WEEK_NUM(EVENT_DATE) WEEK_NUM,
 BO.GET_SAME_DAY(EVENT_DATE) SAME_DAY,
 TO_CHAR(EVENT_DATE, 'DY') WEEK_DAY,
 BO.GET_DATE_MTD(EVENT_DATE) DATE_MTD,
 M.EVENT_DATE,
 M.VERTICAL,
 M.PRODUCT,
 M.REVENUE,
 NULL,
 TO_CHAR(TRUNC(EVENT_DATE, 'mm'), 'MM') MMONTH,
 TO_CHAR(TRUNC(EVENT_DATE, 'dd'), 'DD') DDATE,
 TO_CHAR(TRUNC(EVENT_DATE, 'yyyy'), 'YYYY') YYEAR
  FROM BO.VW_MPESA_VIEW M
 WHERE M.EVENT_DATE >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
   AND M.EVENT_DATE < TRUNC(SYSDATE);